# Cosmos REST Faucet configuration

gaia_home_folder = "/provider-coordinator"
transactions_log = "transactions.csv"
request_timeout    = "86400"

[cosmos]
prefix         = "cosmos"
denomination   = "stake"

[testnets]
    [testnets.provider]
    node_url = "http://165.227.143.45:26658"
    chain_id = "provider"
    faucet_address = "cosmos1w58ehaqlqjujdu4mp6xuemetqlqky6nf6r8nm9"
    daily_cap = "70000000"
    amount_to_send = "5000000"
    tx_fees = "500"
